name: Build and run tests on Ubuntu, Macos and Windows

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-unbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo build && cargo test --verbose

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo build && cargo test --verbose

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo build && cargo test --verbose
